import Head from "next/head"
import Nav from "./Nav"
import {useContextApp} from "./Wrapper"
import Cart from "./Cart";

export default function Layout({children,title}) {
  const context = useContextApp();
  return (
    <div>
      <Head>
          <title>Ecommerce {title ? title : ""}</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Nav/>
      {children}
      {context.open ? <Cart/> : null}
    </div>
  )
}